### ISSUE TITLE
Unsupported keywords

### ISSUE THREAD

**Issue by robhowley** [adidonato/language-hql#2]
It looks like `external`, `string` and `float` aren't supported/picked up by the syntax highlighter. The following table definition 

```
create external table (
  col_one string,
  col_two float
) ;
```

is rendered as

![image](https://cloud.githubusercontent.com/assets/5652308/12057519/f4639d00-af0f-11e5-82a2-560370c8a5cf.png)

whereas the simple table syntax renders as expected ...

![image](https://cloud.githubusercontent.com/assets/5652308/12057570/6ca67f80-af10-11e5-982a-17c934389bd5.png)

Thanks,
Rob

**Comment by robhowley** [comment]
Naive attempt at a solution for the `create external table` go to the first match section at the top of _hql.cson_ and change 

`'match': '(?i:^\\s*(create(?:\\s+or\\s+replace)?)`

`'match': '(?i:^\\s*(create(?:\\s+or\\s+replace)?(?:\\s+external)?)`

Not sure if that misses other cases.

**Comment by adidonato** [comment]
Hi, sorry for the late reply :) I have implemented your change, please let me know if any issues
