### ISSUE TITLE
Error on Atom startup: Duplicate key 'abs'

### ISSUE THREAD

**Issue by juhoautio** [adidonato/language-hql#8]
> Failed to load snippets from '/Users/JuhoAutio/.atom/packages/language-hql/snippets/language-hql.cson'

> /Users/JuhoAutio/.atom/packages/language-hql/snippets/language-hql.cson: Duplicate key 'abs'

**Comment by adidonato** [comment]
Hi, this has been solved, please update to 4.1.1, thanks
